[project]
name = "api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.8",
    "pydantic-settings>=2.7.1",
    "python-multipart>=0.0.20",
    "supabase>=2.12.0",
    "uvicorn>=0.34.0",
]
