name: API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/setup/requirements.txt
          pip install pytest pytest-html requests
      
      - name: Run tests with pytest
        run: |
          cd testing/api-tests
          pytest --html=report.html --self-contained-html
      
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()  # Upload test results even if tests fail
        with:
          name: test-results
          path: testing/api-tests/report.html
          retention-days: 7